/********************************************************************
* candAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error candAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecandAnaDict();
extern void G__cpp_setup_inheritancecandAnaDict();
extern void G__cpp_setup_typetablecandAnaDict();
extern void G__cpp_setup_memvarcandAnaDict();
extern void G__cpp_setup_globalcandAnaDict();
extern void G__cpp_setup_memfunccandAnaDict();
extern void G__cpp_setup_funccandAnaDict();
extern void G__set_cpp_environmentcandAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "candAna.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__candAnaDictLN_TClass;
extern G__linked_taginfo G__candAnaDictLN_TBuffer;
extern G__linked_taginfo G__candAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__candAnaDictLN_TObject;
extern G__linked_taginfo G__candAnaDictLN_TNamed;
extern G__linked_taginfo G__candAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__candAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__candAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__candAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__candAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__candAnaDictLN_TFile;
extern G__linked_taginfo G__candAnaDictLN_TTree;
extern G__linked_taginfo G__candAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__candAnaDictLN_hfcand;
extern G__linked_taginfo G__candAnaDictLN_TAnaTrack;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__candAnaDictLN_TAnaCand;
extern G__linked_taginfo G__candAnaDictLN_pairlEintcOpairlEfloatcOfloatgRsPgR;
extern G__linked_taginfo G__candAnaDictLN_vectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__candAnaDictLN_reverse_iteratorlEvectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__candAnaDictLN_TAna01Event;
extern G__linked_taginfo G__candAnaDictLN_candAna;

/* STUB derived class for protected member access */
