/********************************************************************
* hfcandDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error hfcandDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablehfcandDict();
extern void G__cpp_setup_inheritancehfcandDict();
extern void G__cpp_setup_typetablehfcandDict();
extern void G__cpp_setup_memvarhfcandDict();
extern void G__cpp_setup_globalhfcandDict();
extern void G__cpp_setup_memfunchfcandDict();
extern void G__cpp_setup_funchfcandDict();
extern void G__set_cpp_environmenthfcandDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "hfcand.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__hfcandDictLN_TClass;
extern G__linked_taginfo G__hfcandDictLN_TBuffer;
extern G__linked_taginfo G__hfcandDictLN_TMemberInspector;
extern G__linked_taginfo G__hfcandDictLN_TObject;
extern G__linked_taginfo G__hfcandDictLN_TNamed;
extern G__linked_taginfo G__hfcandDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__hfcandDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hfcandDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__hfcandDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__hfcandDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__hfcandDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__hfcandDictLN_snglhfcand;
extern G__linked_taginfo G__hfcandDictLN_hfcand;

/* STUB derived class for protected member access */
