/********************************************************************
* map_infoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error map_infoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemap_infoDict();
extern void G__cpp_setup_inheritancemap_infoDict();
extern void G__cpp_setup_typetablemap_infoDict();
extern void G__cpp_setup_memvarmap_infoDict();
extern void G__cpp_setup_globalmap_infoDict();
extern void G__cpp_setup_memfuncmap_infoDict();
extern void G__cpp_setup_funcmap_infoDict();
extern void G__set_cpp_environmentmap_infoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "map_info.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__map_infoDictLN_TClass;
extern G__linked_taginfo G__map_infoDictLN_TBuffer;
extern G__linked_taginfo G__map_infoDictLN_TMemberInspector;
extern G__linked_taginfo G__map_infoDictLN_TObject;
extern G__linked_taginfo G__map_infoDictLN_TNamed;
extern G__linked_taginfo G__map_infoDictLN_string;
extern G__linked_taginfo G__map_infoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__map_infoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__map_infoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__map_infoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__map_infoDictLN_map_info;

/* STUB derived class for protected member access */
