/********************************************************************
* snglhfcandDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error snglhfcandDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablesnglhfcandDict();
extern void G__cpp_setup_inheritancesnglhfcandDict();
extern void G__cpp_setup_typetablesnglhfcandDict();
extern void G__cpp_setup_memvarsnglhfcandDict();
extern void G__cpp_setup_globalsnglhfcandDict();
extern void G__cpp_setup_memfuncsnglhfcandDict();
extern void G__cpp_setup_funcsnglhfcandDict();
extern void G__set_cpp_environmentsnglhfcandDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "snglhfcand.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__snglhfcandDictLN_TClass;
extern G__linked_taginfo G__snglhfcandDictLN_TBuffer;
extern G__linked_taginfo G__snglhfcandDictLN_TMemberInspector;
extern G__linked_taginfo G__snglhfcandDictLN_TObject;
extern G__linked_taginfo G__snglhfcandDictLN_TNamed;
extern G__linked_taginfo G__snglhfcandDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__snglhfcandDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__snglhfcandDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__snglhfcandDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__snglhfcandDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__snglhfcandDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__snglhfcandDictLN_snglhfcand;

/* STUB derived class for protected member access */
