/********************************************************************
* TAna01EventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TAna01EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAna01EventDict();
extern void G__cpp_setup_inheritanceTAna01EventDict();
extern void G__cpp_setup_typetableTAna01EventDict();
extern void G__cpp_setup_memvarTAna01EventDict();
extern void G__cpp_setup_globalTAna01EventDict();
extern void G__cpp_setup_memfuncTAna01EventDict();
extern void G__cpp_setup_funcTAna01EventDict();
extern void G__set_cpp_environmentTAna01EventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TAna01Event.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAna01EventDictLN_TClass;
extern G__linked_taginfo G__TAna01EventDictLN_TBuffer;
extern G__linked_taginfo G__TAna01EventDictLN_TMemberInspector;
extern G__linked_taginfo G__TAna01EventDictLN_TObject;
extern G__linked_taginfo G__TAna01EventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAna01EventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAna01EventDictLN_TClonesArray;
extern G__linked_taginfo G__TAna01EventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAna01EventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAna01EventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAna01EventDictLN_TAnaTrack;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TAna01EventDictLN_TAnaVertex;
extern G__linked_taginfo G__TAna01EventDictLN_TAnaCand;
extern G__linked_taginfo G__TAna01EventDictLN_pairlEintcOpairlEfloatcOfloatgRsPgR;
extern G__linked_taginfo G__TAna01EventDictLN_vectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TAna01EventDictLN_reverse_iteratorlEvectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAna01EventDictLN_TAna01Event;

/* STUB derived class for protected member access */
