/********************************************************************
* TAnaTrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TAnaTrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAnaTrackDict();
extern void G__cpp_setup_inheritanceTAnaTrackDict();
extern void G__cpp_setup_typetableTAnaTrackDict();
extern void G__cpp_setup_memvarTAnaTrackDict();
extern void G__cpp_setup_globalTAnaTrackDict();
extern void G__cpp_setup_memfuncTAnaTrackDict();
extern void G__cpp_setup_funcTAnaTrackDict();
extern void G__set_cpp_environmentTAnaTrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TAnaTrack.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAnaTrackDictLN_TClass;
extern G__linked_taginfo G__TAnaTrackDictLN_TBuffer;
extern G__linked_taginfo G__TAnaTrackDictLN_TMemberInspector;
extern G__linked_taginfo G__TAnaTrackDictLN_TObject;
extern G__linked_taginfo G__TAnaTrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAnaTrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaTrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAnaTrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAnaTrackDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAnaTrackDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAnaTrackDictLN_TVector3;
extern G__linked_taginfo G__TAnaTrackDictLN_TAnaTrack;

/* STUB derived class for protected member access */
