/********************************************************************
* TAnaVertexDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TAnaVertexDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAnaVertexDict();
extern void G__cpp_setup_inheritanceTAnaVertexDict();
extern void G__cpp_setup_typetableTAnaVertexDict();
extern void G__cpp_setup_memvarTAnaVertexDict();
extern void G__cpp_setup_globalTAnaVertexDict();
extern void G__cpp_setup_memfuncTAnaVertexDict();
extern void G__cpp_setup_funcTAnaVertexDict();
extern void G__set_cpp_environmentTAnaVertexDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TAnaVertex.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAnaVertexDictLN_TClass;
extern G__linked_taginfo G__TAnaVertexDictLN_TBuffer;
extern G__linked_taginfo G__TAnaVertexDictLN_TMemberInspector;
extern G__linked_taginfo G__TAnaVertexDictLN_TObject;
extern G__linked_taginfo G__TAnaVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAnaVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAnaVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAnaVertexDictLN_TVector3;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TAnaVertexDictLN_TAnaVertex;

/* STUB derived class for protected member access */
