/********************************************************************
* TAnaCandDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TAnaCandDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAnaCandDict();
extern void G__cpp_setup_inheritanceTAnaCandDict();
extern void G__cpp_setup_typetableTAnaCandDict();
extern void G__cpp_setup_memvarTAnaCandDict();
extern void G__cpp_setup_globalTAnaCandDict();
extern void G__cpp_setup_memfuncTAnaCandDict();
extern void G__cpp_setup_funcTAnaCandDict();
extern void G__set_cpp_environmentTAnaCandDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TAnaCand.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAnaCandDictLN_TClass;
extern G__linked_taginfo G__TAnaCandDictLN_TBuffer;
extern G__linked_taginfo G__TAnaCandDictLN_TMemberInspector;
extern G__linked_taginfo G__TAnaCandDictLN_TObject;
extern G__linked_taginfo G__TAnaCandDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAnaCandDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaCandDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAnaCandDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAnaCandDictLN_TVector3;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TAnaCandDictLN_TAnaVertex;
extern G__linked_taginfo G__TAnaCandDictLN_TAnaCand;
extern G__linked_taginfo G__TAnaCandDictLN_pairlEintcOpairlEfloatcOfloatgRsPgR;
extern G__linked_taginfo G__TAnaCandDictLN_vectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TAnaCandDictLN_reverse_iteratorlEvectorlEpairlEintcOpairlEfloatcOfloatgRsPgRcOallocatorlEpairlEintcOpairlEfloatcOfloatgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
